### ISSUE TITLE
Highlighted buttons

### ISSUE THREAD

**Issue by otajor** [daUnicorns/stopwatch#16]
After you click a button it's left with a little blue outline. See screenshot:

<img width="120" alt="screen shot 2016-01-29 at 11 58 33" src="https://cloud.githubusercontent.com/assets/13705650/12675075/ae3f9798-c67f-11e5-8c41-4f637b080ff2.png">

You can fix it with:

``` css
button:focus {
    outline:0;
}
```
